### ISSUE TITLE
Feature: List intersections based on context

### ISSUE THREAD

**Issue by sc0ttbeardsley** [yahoo/zeus#17]
Currently we have a way to expand a list based on a set of dimensions. I would like to define a complete list in master context but them limit that list based on some other context. For example imagine a list of colocations named "colos". In master context it would be complete but under the "region=emea" context it would be limited to only those colocations in Europe.

**Comment by sc0ttbeardsley** [comment]
Here is an example config:

<pre>
# settings.yaml
---
- settings: master
  pops:
    - paris
    - virginia
    - tokyo
    - singapore
- settings:
    region: emea
  pops:
    - paris
- settings:
    region: apac
  pops:
    - tokyo
    - singapore
- settings:
    region: us
  pops:
    - virginia
</pre>

The above config will append to the `pops` list depending on the `region` context. For instance, with the `us` context the list will be: [paris, virginia, tokyo, singapore, virginia]

Maybe the syntax could be something like:

<pre>
- settings:
    region: us
  pops: !intersect
    - virginia
</pre>

Which would provide the list [virginia] for the `us` context.

**Comment by dmorilha-yahoo** [comment]
my suggestion here is to use a dynamic of boolean values:

```
---
- settings: master
  pops: !!dynamic
    paris: true
    virginia: true
    tokyo: true
    singapore: true

---
- settings:
    region: emea
  pops:
    paris: true
    virginia: false
    tokyo: false
    singapore: false
```
